#!/usr/bin/env python3
"""
Backfill captured_at from exif_data for existing photos.

Usage:
    # Dry run - just print what would be updated
    python backfill_captured_at.py

    # Generate SQL file
    python backfill_captured_at.py > updates.sql

    # Apply directly (pipe to psql)
    python backfill_captured_at.py | psql -d hillview

Environment:
    DATABASE_URL or individual PG* variables for connection
"""

import json
import subprocess
import sys
from datetime import datetime, timezone
from typing import Optional


def parse_exif_datetime(value) -> Optional[datetime]:
    """Parse EXIF datetime value and fix corrupted timestamps.

    Handles the bug where milliseconds were written as seconds, causing
    dates like "+58074:03:14 04:05:17". Detects years > 2100 and fixes
    by dividing the timestamp by 1000.

    Returns UTC datetime.
    """
    if value is None:
        return None

    # If it's already a numeric timestamp
    if isinstance(value, (int, float)):
        ts = float(value)
        # Check if this looks like milliseconds (year > 2100)
        if ts > 4102444800:  # 2100-01-01 in seconds
            ts = ts / 1000
        return datetime.fromtimestamp(ts, tz=timezone.utc)

    # String format - try to parse
    value_str = str(value)

    # Handle the corrupted format like "+58074:03:14 04:05:17"
    if value_str.startswith('+'):
        value_str = value_str[1:]

    formats = [
        "%Y:%m:%d %H:%M:%S",
        "%Y-%m-%d %H:%M:%S",
        "%Y:%m:%d %H:%M:%S.%f",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%S.%f",
        "%Y-%m-%dT%H:%M:%SZ",
    ]

    for fmt in formats:
        try:
            dt = datetime.strptime(value_str, fmt)
            if dt.year > 2100:
                # Corrupted timestamp - was milliseconds interpreted as seconds
                ts = dt.timestamp()
                corrected_ts = ts / 1000
                return datetime.fromtimestamp(corrected_ts, tz=timezone.utc)
            return dt.replace(tzinfo=timezone.utc)
        except ValueError:
            continue

    return None


def get_photos_json() -> list:
    """Query photos with exif_data from database using psql."""
    query = """
    SELECT json_agg(row_to_json(t))
    FROM (
        SELECT id, captured_at, exif_data
        FROM photos
        WHERE exif_data IS NOT NULL
    ) t;
    """

    result = subprocess.run(
        ['psql', '-t', '-A', '-c', query],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(f"-- Error querying database: {result.stderr}", file=sys.stderr)
        sys.exit(1)

    output = result.stdout.strip()
    if not output or output == 'null':
        return []

    return json.loads(output)


def main():
    print("-- Backfill captured_at from exif_data")
    print("-- Generated by backfill_captured_at.py")
    print()

    photos = get_photos_json()

    if not photos:
        print("-- No photos with exif_data found")
        return

    print(f"-- Found {len(photos)} photos with exif_data")
    print()

    updates = []
    skipped_no_datetime = 0
    skipped_already_set = 0
    corrupted_fixed = 0

    for photo in photos:
        photo_id = photo['id']
        current_captured_at = photo.get('captured_at')
        exif_data = photo.get('exif_data')

        if not exif_data:
            continue

        # exif_data structure: {'data': {...raw exiftool output...}, 'gps': {...}, ...}
        raw_data = exif_data.get('data', {})

        # Try DateTimeOriginal first, then CreateDate
        datetime_original = raw_data.get('DateTimeOriginal') or raw_data.get('CreateDate')

        if not datetime_original:
            skipped_no_datetime += 1
            continue

        parsed_dt = parse_exif_datetime(datetime_original)

        if not parsed_dt:
            print(f"-- WARNING: Could not parse DateTimeOriginal for {photo_id}: {datetime_original}")
            continue

        # Check if this was a corrupted timestamp
        if isinstance(datetime_original, str) and datetime_original.startswith('+'):
            corrupted_fixed += 1
            print(f"-- CORRUPTED: {photo_id}: {datetime_original} -> {parsed_dt.isoformat()}")

        # Format for PostgreSQL
        # Format as naive UTC (no timezone) to match TIMESTAMP WITHOUT TIME ZONE column
        new_captured_at = parsed_dt.strftime("%Y-%m-%d %H:%M:%S")

        # Check if already set correctly
        if current_captured_at:
            # Parse current value for comparison
            if isinstance(current_captured_at, str):
                try:
                    current_dt = datetime.fromisoformat(current_captured_at.replace('Z', '+00:00'))
                    # Allow 1 second tolerance for comparison
                    if abs((current_dt - parsed_dt).total_seconds()) < 1:
                        skipped_already_set += 1
                        continue
                except ValueError:
                    pass

        updates.append({
            'id': photo_id,
            'old': current_captured_at,
            'new': new_captured_at,
            'raw': datetime_original
        })

    print(f"-- Skipped {skipped_no_datetime} photos without DateTimeOriginal")
    print(f"-- Skipped {skipped_already_set} photos already set correctly")
    print(f"-- Fixed {corrupted_fixed} corrupted timestamps (year > 2100)")
    print(f"-- Updates needed: {len(updates)}")
    print()

    if not updates:
        print("-- No updates needed")
        return

    print("BEGIN;")
    print()

    for update in updates:
        print(f"-- Photo {update['id']}: {update['old']} -> {update['new']} (from: {update['raw']})")
        # Escape single quotes in photo_id (UUIDs shouldn't have them, but be safe)
        safe_id = update['id'].replace("'", "''")
        print(f"UPDATE photos SET captured_at = '{update['new']}' WHERE id = '{safe_id}';")
        print()

    print("COMMIT;")
    print()
    print(f"-- Total: {len(updates)} updates")


if __name__ == '__main__':
    main()
