/**
 * Terrain bench test helpers: serve the deterministic fixtures (generated by
 * enrich/terrain/make_fixture.py) through route stubs, and map fixture pixel
 * coordinates to page/canvas positions.
 *
 * golden.json is the cross-language contract: pixel targets chosen in Python
 * with the geo coordinates Python's renderer computes for them. The specs
 * click those pixels and assert the browser agrees within epsilon.
 */
import fs from 'node:fs';
import path from 'node:path';
import type { Page } from '@playwright/test';

const FIX = path.join(import.meta.dirname, '..', 'fixtures');
const read = (f: string) => fs.readFileSync(path.join(FIX, f));

export const meta = JSON.parse(read('meta.json').toString()) as {
	width: number;
	height: number;
	lat: number;
	lon: number;
	[k: string]: unknown;
};
export const golden = JSON.parse(read('golden.json').toString()) as {
	viewpoint: { lat: number; lon: number };
	summit: GoldenPick;
	far_ridge: GoldenPick;
	near_slope: GoldenPick;
	sky: { col: number; row: number };
	tolerance_deg: number;
};
export interface GoldenPick {
	col: number;
	row: number;
	lat: number;
	lon: number;
	distance_m: number;
	azimuth_deg: number;
}

export const RENDER_ID = 'fixture-render-0000';
export const SKY_RGB: [number, number, number] = [167, 205, 240];

export function renderRow(overrides: Record<string, unknown> = {}) {
	return {
		id: RENDER_ID,
		photo_id: null,
		lat: golden.viewpoint.lat,
		lon: golden.viewpoint.lon,
		params: {},
		status: 'done',
		error: null,
		meta,
		has_depth: true,
		has_preview: true,
		worker: 'fixture',
		enqueued_at: '2026-07-23T09:00:00.000Z',
		finished_at: '2026-07-23T09:00:05.000Z',
		...overrides
	};
}

/** Stub all /api/terrain/* the bench touches. `rows` is a live reference so
 * lifecycle tests can mutate it between refreshes. */
export async function stubTerrainApi(page: Page, rows: () => unknown[]) {
	await page.route('**/api/terrain/**', async (route) => {
		const url = route.request().url();
		if (url.endsWith('/depth')) {
			return route.fulfill({ body: read('depth.bin'), contentType: 'application/octet-stream' });
		}
		if (url.endsWith('/preview')) {
			return route.fulfill({ body: read('preview.jpg'), contentType: 'image/jpeg' });
		}
		if (url.includes('/terrain/enqueue')) {
			return route.fulfill({ json: { queued: RENDER_ID } });
		}
		return route.fulfill({ json: { renders: rows() } });
	});
}

const wrap01 = (x: number) => ((x % 1) + 1) % 1;

/** Fixture pixel center → canvas CSS coords through the viewer's LIVE rect
 * (mirrors peakLabels.texToCanvas). The canvas no longer coincides with the
 * texture: it fills its CSS box and the vertical window follows the canvas
 * aspect, so a fixed col/row→px mapping would land off the strip. */
async function cssPoint(page: Page, pick: { col: number; row: number }) {
	const box = (await page.getByTestId('terrain-canvas').boundingBox())!;
	const rect = await page.evaluate(
		() =>
			(
				window as unknown as {
					__hvTerrainViewer?: {
						getRect(): { x1: number; y1: number; x2: number; y2: number } | null;
					};
				}
			).__hvTerrainViewer!.getRect()!
	);
	const a = meta.height / meta.width;
	const u = (pick.col + 0.5) / meta.width;
	const v = (pick.row + 0.5) / meta.height;
	const dx = wrap01(u - wrap01(rect.x1));
	return {
		box,
		cssX: (dx / (rect.x2 - rect.x1)) * box.width,
		cssY: ((v * a - rect.y1) / (rect.y2 - rect.y1)) * box.height
	};
}

/** Page coordinates of a fixture pixel's center under the current view. */
export async function pagePoint(page: Page, pick: { col: number; row: number }) {
	const { box, cssX, cssY } = await cssPoint(page, pick);
	return { x: box.x + cssX, y: box.y + cssY };
}

/** RGBA at a fixture pixel via the viewer's readPixel hook (CSS coords are
 * canvas-relative; redraw+read happens synchronously inside the page). */
export async function readPixelAt(page: Page, pick: { col: number; row: number }) {
	const { cssX, cssY } = await cssPoint(page, pick);
	return page.evaluate(
		([x, y]) =>
			(
				window as unknown as {
					__hvTerrainViewer?: { readPixel(x: number, y: number): number[] };
				}
			).__hvTerrainViewer!.readPixel(x, y),
		[cssX, cssY]
	);
}

export function colorDist(a: number[], b: [number, number, number]) {
	return Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
}

/** Zoom so the texture's full height fills the canvas with the target's
 * column centered — single-pixel color reads are meaningless in the squeezed
 * reset view (a texture row maps to a fraction of a device pixel and the
 * shader resolves the pixel to a neighbouring row). This reproduces the
 * framing the old texture-aspect-locked canvas gave every sample. */
export async function frameTarget(page: Page, pick: { col: number; row: number }) {
	const a = meta.height / meta.width;
	const u = (pick.col + 0.5) / meta.width;
	await page.evaluate(
		([u_, a_]) => {
			const v = (
				window as unknown as {
					__hvTerrainViewer?: {
						getRect(): { x1: number; y1: number; x2: number; y2: number } | null;
						setRect(r: { x1: number; y1: number; x2: number; y2: number }): void;
					};
				}
			).__hvTerrainViewer!;
			const r = v.getRect()!;
			// uWindow that makes vWindow exactly the full texture height
			const w = ((r.x2 - r.x1) * a_) / (r.y2 - r.y1);
			v.setRect({ x1: u_ - w / 2, y1: 0, x2: u_ + w / 2, y2: a_ });
		},
		[u, a]
	);
}

/** Selects the fixture render and waits for the canvas to actually paint
 * terrain (the summit pixel stops being background/blank). */
export async function openFixtureRender(page: Page) {
	await page.goto('/terrain');
	await page.getByTestId('terrain-row').first().click();
	await page
		.waitForFunction(() => {
			const v = (
				window as unknown as {
					__hvTerrainViewer?: { readPixel(x: number, y: number): number[] };
				}
			).__hvTerrainViewer;
			if (!v) return false;
			const px = v.readPixel(5, 5); // top-left: sky once loaded, black before
			return px[0] + px[1] + px[2] > 60;
		})
		.catch(() => {
			throw new Error('terrain canvas never painted — viewer failed to load fixtures');
		});
}
