"""Add SET NULL cascade to security audit user_id FK

Revision ID: 93bf4b05512f
Revises: c001_add_security_audit_log
Create Date: 2025-08-21 01:31:29.289889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93bf4b05512f'
down_revision: Union[str, None] = 'c001_add_security_audit_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed PostGIS table drops as they are managed by the extension
    op.alter_column('photos', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_test',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'MODERATOR', name='userrole'),
               nullable=True)
    
    # Add SET NULL cascade to security_audit_log.user_id foreign key
    op.drop_constraint('security_audit_log_user_id_fkey', 'security_audit_log', type_='foreignkey')
    op.create_foreign_key('security_audit_log_user_id_fkey', 'security_audit_log', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore original foreign key without SET NULL cascade
    op.drop_constraint('security_audit_log_user_id_fkey', 'security_audit_log', type_='foreignkey')
    op.create_foreign_key('security_audit_log_user_id_fkey', 'security_audit_log', 'users', ['user_id'], ['id'])
    
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', 'MODERATOR', name='userrole'),
               nullable=False)
    op.alter_column('users', 'is_test',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('photos', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Note: Removed PostGIS table creates as they are managed by the extension
    # ### end Alembic commands ###