#!/usr/bin/env python3
"""Point the whole stack at one host by rendering a profile into the env files.

The host is declared across files read by different things at different times —
docker compose at container start, Vite at dev-server start, Playwright at run
start — so passing env vars per invocation is unworkable: you would have to
remember the whole set, every time, for every tool. This owns the swap instead.

    ./scripts/set_host.py                    show the current profile
    ./scripts/set_host.py --list             show every profile
    ./scripts/set_host.py jj-ygg             switch
    ./scripts/set_host.py jj-ygg --keep-db   switch, keep existing photos

Profiles are named <machine>-<how you reach it>: `raw` is every service on its
own port over plain HTTP (the only thing Android can use), `ygg` is the single
HTTPS/HTTP-2 origin published over Yggdrasil, `local` is a Caddy origin that is
only reachable on the LAN. jj has no `local` — its Caddy name is an ygg name.

Switching clears the dev database by default: a stored photo's URLs were built
from the PICS_URL in force when it was written, so rows made under the previous
profile point at a host this one does not serve. Pass --keep-db to skip that.

Rather than editing your declarations in place, it appends a delimited block:

    # >>> set_host: jj-ygg ...
    WORKER_URL=...
    # <<< set_host

Later declarations win in both consumers, so the block is authoritative without
touching a line you wrote, the active profile is self-documenting in the file,
and reverting is deleting the block. Re-running replaces the block rather than
stacking another one.

Profiles live in scripts/host_profiles.py. Restart the stack afterwards — api
and worker read these at container start:

    docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
"""
import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request

from host_profiles import PROFILES, unset_keys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BEGIN = "# >>> set_host:"
END = "# <<< set_host"

COMPOSE = ["docker", "compose", "-f", "docker-compose.yml", "-f", "docker-compose.dev.yml"]

# Always the published api port, in every profile: Caddy proxies /api to this
# same port, so it does not move when the browser-facing host does.
CLEAR_DB_URL = "http://localhost:8055/api/debug/clear-database"


def read(relpath):
	path = os.path.join(REPO, relpath)
	if not os.path.exists(path):
		return None
	with open(path) as handle:
		return handle.read()


def strip_block(text):
	"""Drop any existing managed block, so we never stack two."""
	return re.sub(
		rf"\n*{re.escape(BEGIN)}.*?{re.escape(END)}\n?",
		"\n",
		text,
		flags=re.DOTALL,
	)


def active_value(text, key):
	"""Last active (uncommented) value of `key`, which is the one that wins."""
	found = None
	for match in re.finditer(rf"^\s*{re.escape(key)}=(.*)$", text, re.MULTILINE):
		found = match.group(1)
	return found


def rewrite_pools(text, pools):
	"""Take the live FILE_POOLS and swap only its files-pool urls, by path.

	Read from the file rather than carried in the profile so that non-files
	pools — and any edit you make to them — survive a switch untouched.
	"""
	raw = active_value(text, "FILE_POOLS")
	if raw is None:
		return None
	try:
		parsed = json.loads(raw)
	except json.JSONDecodeError as err:
		sys.exit(f"set_host: FILE_POOLS is not valid JSON ({err}) — fix it by hand")
	for pool in parsed:
		if pool.get("type") != "files":
			continue
		url = pools.get(pool.get("path"))
		if url is None:
			print(f"  ! FILE_POOLS: no mapping for path {pool.get('path')!r}; "
			      f"leaving {pool.get('url')!r}")
			continue
		pool["url"] = url
	return json.dumps(parsed, separators=(",", ":"))


def render(relpath, name, values):
	"""Write the managed block for one file. Returns the pairs written."""
	path = os.path.join(REPO, relpath)
	text = read(relpath)
	if text is None:
		print(f"  - {relpath}: missing, skipped")
		return []

	body = strip_block(text).rstrip("\n")
	# None omits the key entirely (the file's own declaration, if any, stands);
	# "" declares it empty, which is how you turn OFF a feature the base file
	# switches on — the block can only add a later declaration, never delete an
	# earlier one, so overriding with empty is the only way down.
	pairs = [(key, value) for key, value in values.items() if value is not None]
	if pairs:
		lines = [
			f"{BEGIN} {name} — generated by scripts/set_host.py, edits here are overwritten",
			*(f"{key}={value}" for key, value in pairs),
			END,
		]
		body = body + "\n\n" + "\n".join(lines)

	with open(path, "w") as handle:
		handle.write(body + "\n")
	return pairs


def compose_resolved():
	"""What compose actually resolves, so a precedence surprise cannot pass silently."""
	try:
		out = subprocess.run(
			COMPOSE + ["config", "--format", "json"],
			cwd=REPO, capture_output=True, text=True, timeout=60,
		)
	except (OSError, subprocess.SubprocessError) as err:
		return None, f"could not run docker compose ({err})"
	if out.returncode != 0:
		return None, (out.stderr or "").strip().splitlines()[-1:] or ["compose config failed"]
	try:
		config = json.loads(out.stdout)
	except json.JSONDecodeError:
		return None, "compose config was not JSON"

	resolved = {}
	for service in config.get("services", {}).values():
		env = service.get("environment") or {}
		if isinstance(env, list):
			env = dict(
				item.split("=", 1) for item in env if isinstance(item, str) and "=" in item
			)
		for key in ("PICS_URL", "WORKER_URL"):
			if env.get(key):
				resolved.setdefault(key, env[key])
	return resolved, None


def verify(expected):
	"""Confirm compose sees the block's values (the last-wins assumption)."""
	resolved, problem = compose_resolved()
	if resolved is None:
		print(f"\nnot verified: {problem}")
		print("  check by hand: docker compose -f docker-compose.yml -f docker-compose.dev.yml config")
		return True
	ok = True
	for key, want in expected.items():
		got = resolved.get(key)
		if got is None:
			continue
		if got != want:
			ok = False
			print(f"\n! compose resolves {key}={got!r}, not the {want!r} just written.")
			print("  Something later in the file, or the shell environment, is overriding")
			print("  the block — this file needs in-place replacement instead of append.")
	if ok:
		print("\nverified: compose resolves the values just written")
	return ok


def clear_database():
	"""Wipe the dev database, because rows outlive the profile that made them.

	A stored photo's URLs are built from PICS_URL as it was when the row was
	written, so everything uploaded under the previous profile now points at a
	host this one does not serve. That reads as broken images and sends you
	debugging the wrong thing entirely.

	Best-effort: a stack that is down is not an error here — you are about to
	restart it anyway — so say what to re-run and carry on.
	"""
	try:
		with urllib.request.urlopen(
			urllib.request.Request(CLEAR_DB_URL, method="POST"), timeout=10
		) as response:
			if 200 <= response.status < 300:
				print("  cleared the dev database (its rows held old-host URLs)")
				return True
			print(f"  ! clear-database answered {response.status}")
	except (urllib.error.URLError, OSError) as err:
		print(f"  ! could not clear the database ({err})")
	print(f"    re-run once the stack is up:  curl -X POST {CLEAR_DB_URL}")
	return False


def current():
	text = read("frontend/.env") or ""
	match = re.search(rf"{re.escape(BEGIN)} (\S+)", text)
	if match:
		return match.group(1)
	backend = active_value(text, "VITE_BACKEND")
	for name, profile in PROFILES.items():
		if backend and backend == profile.get("frontend_env", {}).get("VITE_BACKEND"):
			return name
	return None


def describe_current():
	"""Say which profile is live and what Playwright will hit — and warn if that
	origin carries the flake class.

	Run as a preflight (see run_tests.sh) because the failure it predicts is
	awful to diagnose from the inside: over HTTP/1.1 the ~6-connections-per-origin
	cap lets SSE streams and lazy chunks starve asset fetches, which surfaces as
	"Importing a module script failed", a page with no CSS, a login that never
	navigates, or a 90s stalled-request timeout — none of which name their cause.
	Better to say it up front than to let someone re-run three times and then go
	hunting through a trace.
	"""
	name = current()
	url = active_value(read(".env") or "", "FRONTEND_URL")
	print(f"host profile: {name or 'unrecognised'}")
	if url:
		print(f"playwright targets: {url}")
	else:
		print("playwright targets: http://localhost:8212 (dev server it spawns itself)")

	if not url or url.startswith("http://"):
		print("  ! plain HTTP/1.1 origin — the connection-cap flake class is ACTIVE here")
		print("    (stalled chunks / module-script errors, worst on WebKit + Firefox).")
		print("    For a clean run:  ./scripts/set_host.py jj-ygg")
	return 0


def main():
	parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
	parser.add_argument("profile", nargs="?", help="profile to switch to")
	parser.add_argument("--list", action="store_true", help="list profiles and exit")
	parser.add_argument("--keep-db", action="store_true",
	                    help="do not clear the dev database (keeps rows whose "
	                         "photo URLs still point at the previous host)")
	args = parser.parse_args()

	if args.list:
		for name, profile in PROFILES.items():
			missing = unset_keys(profile)
			flag = f"  [incomplete: {len(missing)} unset]" if missing else ""
			print(f"{name:<12} {profile['summary']}{flag}")
			print(f"{'':<12} {profile['note']}")
		return 0

	if args.profile is None:
		return describe_current()

	if args.profile not in PROFILES:
		sys.exit(f"set_host: unknown profile {args.profile!r}\n"
		         f"  known: {', '.join(PROFILES)}\n"
		         f"  see:   ./scripts/set_host.py --list")

	profile = PROFILES[args.profile]
	missing = unset_keys(profile)
	if missing:
		sys.exit(
			f"set_host: profile {args.profile!r} is incomplete — these are still unset:\n"
			+ "".join(f"  {key}\n" for key in missing)
			+ "Fill them in scripts/host_profiles.py first; refusing to write a\n"
			  "half-configured stack that would fail in confusing ways."
		)

	print(f"set_host: {args.profile} — {profile['summary']}")

	env_values = dict(profile["env"])
	pools = rewrite_pools(strip_block(read(".env") or ""), profile["pools"])
	if pools:
		env_values["FILE_POOLS"] = pools
	env_values["FRONTEND_URL"] = profile["frontend_url"]

	for key, value in render(".env", args.profile, env_values):
		print(f"  .env           {key}={value}")
	for key, value in render("frontend/.env", args.profile, profile["frontend_env"]):
		print(f"  frontend/.env  {key}={value}")

	if not args.keep_db:
		clear_database()

	ok = verify({
		"PICS_URL": profile["env"]["PICS_URL"],
		"WORKER_URL": profile["env"]["WORKER_URL"],
	})

	print("\nrestart the stack so api/worker pick this up:")
	print("  docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d")
	if profile["frontend_url"]:
		print("\nthis profile serves the BUILT frontend container, which holds no source —")
		print("rebuild it after frontend/src changes or you test stale code:")
		print("  docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build frontend")
	return 0 if ok else 1


if __name__ == "__main__":
	sys.exit(main())
