#!/bin/bash
#
# Run JVM-level (local, no emulator/device) unit tests for the
# tauri-plugin-hillview Android plugin via gradle. Used from package.json
# and scripts/validate.sh.
#
# Requires src-tauri/gen/android/ to have been generated AND bootstrapped, both
# of which scripts/android/debug-init.sh does (`tauri android init` followed by
# scripts/patch-android-gen-files.py, whose first step emits the gradle glue).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ANDROID_DIR="$PROJECT_ROOT/src-tauri/gen/android"

if [ ! -x "$ANDROID_DIR/gradlew" ]; then
    echo "❌ Tauri Android project not generated at: $ANDROID_DIR"
    echo "   Run 'bun run android:debug:init' (or any android:* command) first"
    echo "   to have Tauri generate the gradle project."
    exit 1
fi

# settings.gradle does `apply from: 'tauri.settings.gradle'`, and that file --
# which is what declares the :tauri-plugin-hillview subproject this task lives in
# -- is written by tauri-build during an Android cargo build, not by
# `tauri android init`. Say so here instead of letting gradle report a bare
# "Could not read script" two screens down.
if [ ! -f "$ANDROID_DIR/tauri.settings.gradle" ]; then
    echo "❌ Android gradle project not bootstrapped: $ANDROID_DIR/tauri.settings.gradle is missing"
    echo "   It is generated by tauri-build during an Android cargo build."
    echo "   Run './scripts/patch-android-gen-files.py' (the step that emits it),"
    echo "   or any full Android build ('./scripts/android/debug-build.sh')."
    exit 1
fi

cd "$ANDROID_DIR"
exec ./gradlew :tauri-plugin-hillview:testDebugUnitTest "$@"
