[default]
description = "Default permissions for the plugin"
permissions = [
	"allow-start-sensor",
	"allow-stop-sensor",
	"allow-register-listener",
	"allow-start-precise-location-listener",
	"allow-stop-precise-location-listener",
	"allow-retry-failed-uploads",
	"allow-store-auth-token",
	"allow-get-auth-token",
	"allow-clear-auth-token",
	"allow-refresh-auth-token",
	"allow-is-token-expired",
	"allow-check-camera-permission",
	"allow-request-camera-permission",
	"allow-get-notification-settings",
	"allow-set-notification-settings",
	"allow-check-tauri-permissions",
	"allow-request-tauri-permission",
	"allow-test-show-notification",
	"allow-refresh-photo-scan",
	"allow-import-photos",
	"allow-share-photo",
	"allow-photo-worker-process",
	"allow-get-push-distributors",
	"allow-get-push-registration-status",
	"allow-select-push-distributor",
	"allow-get-intent-data",
	"allow-poll-messages",
	"allow-cmd",
]
